### ISSUE TITLE
Do sites need to be named sequentially?

### ISSUE THREAD

**Issue by patchcervan** [r-glennie/occuR#3]
Hi @r-glennie, thanks so much for the sharing package. I have to run hundreds of multi-year occupancy models and this package makes it super efficient!

One question, I found the condition that sites need to be named sequentially a bit restrictive. Sequentially in the sense that sites need to be labelled from 1 to max(site) without missing any numbers in the sequence. 

From line #223 in occu_tmb.R:

```
# check site data 
num <- site_data[, .(max = max(site), n = uniqueN(site))]
if (any(num$max != num$n)) stop("site_data has missing sites or sites are mis-numered: ", num[which(num$max  != num$n,)])
```

Sometimes, one might decide to remove sites from the analysis, and is then forced to re-label all other sites. It is not a major issue, but I don't completely understand the reason why. I was thinking alternative ways to perhaps write this condition but I couldn't pinpoint the exact problem to prevent. You probably have a better idea of why non-sequential sites are a problem?

Thanks!

Here is a toy example of what I am talking about:

```
library(dplyr)
library(occuR)

# Parameters for simulating data
psi <- 0.8
p <- 0.9
nsites <- 5
noccasions <- 1
nvisits <- 10

## Name sites sequentially and fit model ##

sims <- data.frame(site = rep(seq_len(nsites), each = nvisits), # this labels sites sequentially
                   occasion = 1,
                   visit = rep(seq_len(nvisits), times = nsites),
                   occu = rep(rbinom(nsites, 1, psi), each = nvisits)) %>%
    mutate(obs = rbinom(nrow(.), 1, psi*p*occu))

site_data <- sims %>%
    group_by(site) %>%
    summarize(occasion = unique(occasion)) %>%
    data.table::as.data.table()

visit_data <- sims %>%
    data.table::as.data.table()

# Fit simple model (works well with all sites)
mod <- occuR::fit_occu(list(psi ~ 1, p ~ 1), visit_data, site_data)

## DON'T name sites sequentially and fit model ##

# Remove one site
site_data <- site_data %>%
    filter(site != 2)

visit_data <- visit_data %>%
    filter(site != 2)

# Fit simple model (doesn't work, because there is no site number 2)
mod <- occuR::fit_occu(list(psi ~ 1, p ~ 1), visit_data, site_data)
```

**Comment by r-glennie** [comment]
Thanks @patchcervan for highlighting this. I have a tendency to be prescriptive with the inputs I expect from users simply to try to avoid errors. In a previous version of the package, I think I needed sites to be sequentially numbered, but I don't think this is required for the current version. I decided to keep it because I thought it might prevent users accidently losing sites but I can see how it would be annoying to enforce this, so I have removed it in commit ef0e0069fbcfa780679b21e10053dfb9146b6685. 

Hope you find the package useful and please do keep bringing up issues!

**Comment by patchcervan** [comment]
Thanks! I hope it doesn't cause trouble :)

**Comment by r-glennie** [comment]
I hope so too! I had a look through the code and ran some tests / examples and there was no issues.
