### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by bowlerbear** [r-glennie/occuR#4]
Hi Richard,

This looks like a super useful package!! I have been trying to fit occupancy models with splines in Stan and Jags - but its slow.

However, I have a problem. I am trying to install the package on our HPC server (since I have lots of species) but it isnt working. I discussed with our IT guys and they said:

"The problem is, that for whatever reason, this R package is trying to install itself to where R is installed, not to your home directory. That's why you get the error about not having write permissions to the location where R is installed.
I even tried from a clean slate, i.e. I removed my `~/R` directory. Normally, when using `install_packages` or `install_github`, R will ask you where to install the packages, and suggests `~/R` if you don't have it already. That's not the case with this R package and that's why it's broken.
"

Any ideas of how to fix this?

Cheers,

Diana

**Comment by patchcervan** [comment]
This worked for me:

devtools::install_github("r-glennie/occuR", type = "source", lib = "directorywhereyouwanttoinstall")

We also have permission issues with the default R package library at our HPC (for any package, not just occuR), so we need to have a directory with the installed packages under our personal directory.

**Comment by bowlerbear** [comment]
thanks @patchcervan  that did it!

**Comment by r-glennie** [comment]
Thanks @patchcervan for working this out!
